package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name = "cargo", catalog = "angelica")
public class Cargo implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private Set<Ficha> fichas = new HashSet<Ficha>(0);

	public Cargo() {
	}

	public Cargo(int codigo) {
		this.codigo = codigo;
	}

	public Cargo(int codigo, String nombre, Set<Ficha> fichas) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.fichas = fichas;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cargo")
	public Set<Ficha> getFichas() {
		return this.fichas;
	}

	public void setFichas(Set<Ficha> fichas) {
		this.fichas = fichas;
	}

}
