package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "angelica")
public class Cliente implements java.io.Serializable {

	private String rut;
	private String nombre;
	private String razonSocial;
	private String fechaPago;
	private String valorInforme;
	private String entregaInforme;
	private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);

	public Cliente() {
	}

	public Cliente(String rut) {
		this.rut = rut;
	}

	public Cliente(String rut, String nombre, String razonSocial,
			String fechaPago, String valorInforme, String entregaInforme,
			Set<Sucursal> sucursals) {
		this.rut = rut;
		this.nombre = nombre;
		this.razonSocial = razonSocial;
		this.fechaPago = fechaPago;
		this.valorInforme = valorInforme;
		this.entregaInforme = entregaInforme;
		this.sucursals = sucursals;
	}

	@Id
	@Column(name = "rut", unique = true, nullable = false, length = 10)
	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "razonSocial", length = 45)
	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	@Column(name = "fechaPago", length = 45)
	public String getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(String fechaPago) {
		this.fechaPago = fechaPago;
	}

	@Column(name = "valorInforme", length = 45)
	public String getValorInforme() {
		return this.valorInforme;
	}

	public void setValorInforme(String valorInforme) {
		this.valorInforme = valorInforme;
	}

	@Column(name = "entregaInforme", length = 45)
	public String getEntregaInforme() {
		return this.entregaInforme;
	}

	public void setEntregaInforme(String entregaInforme) {
		this.entregaInforme = entregaInforme;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Sucursal> getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set<Sucursal> sucursals) {
		this.sucursals = sucursals;
	}

}
