package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "contacto", catalog = "angelica")
public class Contacto implements java.io.Serializable {

	private String rut;
	private Sucursal sucursal;
	private String nombre;
	private String telefono;
	private String email;

	public Contacto() {
	}

	public Contacto(String rut) {
		this.rut = rut;
	}

	public Contacto(String rut, Sucursal sucursal, String nombre,
			String telefono, String email) {
		this.rut = rut;
		this.sucursal = sucursal;
		this.nombre = nombre;
		this.telefono = telefono;
		this.email = email;
	}

	@Id
	@Column(name = "rut", unique = true, nullable = false, length = 10)
	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSucursal")
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
