package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "angelica")
public class Estado implements java.io.Serializable {

	private String codigo;
	private String descripcion;
	private Set<Ficha> fichas = new HashSet<Ficha>(0);

	public Estado() {
	}

	public Estado(String codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public Estado(String codigo, String descripcion, Set<Ficha> fichas) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.fichas = fichas;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false, length = 3)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<Ficha> getFichas() {
		return this.fichas;
	}

	public void setFichas(Set<Ficha> fichas) {
		this.fichas = fichas;
	}

}
