package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ficha generated by hbm2java
 */
@Entity
@Table(name = "ficha", catalog = "angelica")
public class Ficha implements java.io.Serializable {

	private Integer id;
	private Sucursal sucursal;
	private Postulante postulante;
	private Estado estado;
	private Cargo cargo;
	private String valorInforme;
	private byte internoExterno;
	private Date fechaSolicitud;
	private Date fechaEntrevista;
	private Date fechaInforme;
	private String resultado;
	private String comentarios;
	private String curriculum;
	private String informe;
	private String perfil;

	public Ficha() {
	}

	public Ficha(Sucursal sucursal, Postulante postulante, Estado estado,
			Cargo cargo, String valorInforme, byte internoExterno,
			Date fechaSolicitud) {
		this.sucursal = sucursal;
		this.postulante = postulante;
		this.estado = estado;
		this.cargo = cargo;
		this.valorInforme = valorInforme;
		this.internoExterno = internoExterno;
		this.fechaSolicitud = fechaSolicitud;
	}

	public Ficha(Sucursal sucursal, Postulante postulante, Estado estado,
			Cargo cargo, String valorInforme, byte internoExterno,
			Date fechaSolicitud, Date fechaEntrevista, Date fechaInforme,
			String resultado, String comentarios, String curriculum,
			String informe, String perfil) {
		this.sucursal = sucursal;
		this.postulante = postulante;
		this.estado = estado;
		this.cargo = cargo;
		this.valorInforme = valorInforme;
		this.internoExterno = internoExterno;
		this.fechaSolicitud = fechaSolicitud;
		this.fechaEntrevista = fechaEntrevista;
		this.fechaInforme = fechaInforme;
		this.resultado = resultado;
		this.comentarios = comentarios;
		this.curriculum = curriculum;
		this.informe = informe;
		this.perfil = perfil;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSucursal", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rutPostulante", nullable = false)
	public Postulante getPostulante() {
		return this.postulante;
	}

	public void setPostulante(Postulante postulante) {
		this.postulante = postulante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigoCargo", nullable = false)
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@Column(name = "valorInforme", nullable = false, length = 45)
	public String getValorInforme() {
		return this.valorInforme;
	}

	public void setValorInforme(String valorInforme) {
		this.valorInforme = valorInforme;
	}

	@Column(name = "internoExterno", nullable = false)
	public byte getInternoExterno() {
		return this.internoExterno;
	}

	public void setInternoExterno(byte internoExterno) {
		this.internoExterno = internoExterno;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaSolicitud", nullable = false, length = 19)
	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEntrevista", length = 19)
	public Date getFechaEntrevista() {
		return this.fechaEntrevista;
	}

	public void setFechaEntrevista(Date fechaEntrevista) {
		this.fechaEntrevista = fechaEntrevista;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaInforme", length = 19)
	public Date getFechaInforme() {
		return this.fechaInforme;
	}

	public void setFechaInforme(Date fechaInforme) {
		this.fechaInforme = fechaInforme;
	}

	@Column(name = "resultado", length = 45)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@Column(name = "comentarios", length = 45)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "curriculum", length = 256)
	public String getCurriculum() {
		return this.curriculum;
	}

	public void setCurriculum(String curriculum) {
		this.curriculum = curriculum;
	}

	@Column(name = "informe", length = 256)
	public String getInforme() {
		return this.informe;
	}

	public void setInforme(String informe) {
		this.informe = informe;
	}

	@Column(name = "perfil", length = 256)
	public String getPerfil() {
		return this.perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

}
