package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", catalog = "angelica")
public class Grupo implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Grupo() {
	}

	public Grupo(int codigo) {
		this.codigo = codigo;
	}

	public Grupo(int codigo, String nombre, Set<Usuario> usuarios) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
