package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "sucursal", catalog = "angelica")
public class Sucursal implements java.io.Serializable {

	private int id;
	private Cliente cliente;
	private String nombre;
	private String direccion;
	private String telefono;
	private Set<Ficha> fichas = new HashSet<Ficha>(0);
	private Set<Contacto> contactos = new HashSet<Contacto>(0);

	public Sucursal() {
	}

	public Sucursal(int id) {
		this.id = id;
	}

	public Sucursal(int id, Cliente cliente, String nombre, String direccion,
			String telefono, Set<Ficha> fichas, Set<Contacto> contactos) {
		this.id = id;
		this.cliente = cliente;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.fichas = fichas;
		this.contactos = contactos;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rutCliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "direccion", length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Ficha> getFichas() {
		return this.fichas;
	}

	public void setFichas(Set<Ficha> fichas) {
		this.fichas = fichas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

}
