package cl.obeay.angelica.model;

// Generated 18-04-2016 02:42:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "angelica")
public class Usuario implements java.io.Serializable {

	private String login;
	private Grupo grupo;
	private String rut;
	private String password;

	public Usuario() {
	}

	public Usuario(String login) {
		this.login = login;
	}

	public Usuario(String login, Grupo grupo, String rut, String password) {
		this.login = login;
		this.grupo = grupo;
		this.rut = rut;
		this.password = password;
	}

	@Id
	@Column(name = "login", unique = true, nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigogrupo")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@Column(name = "rut", length = 10)
	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
